# Generated by Django 4.1.2 on 2022-10-18 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VulInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vul_name', models.CharField(max_length=30)),
                ('vul_id', models.IntegerField()),
                ('vul_desc', models.CharField(max_length=300)),
            ],
        ),
    ]
