# Generated by Django 4.1.2 on 2022-10-19 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebVul', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('user_name', models.CharField(max_length=30)),
                ('user_pwd', models.CharField(max_length=100)),
                ('user_level', models.IntegerField()),
            ],
        ),
    ]
