# Generated by Django 4.1.2 on 2022-11-02 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebVul', '0002_loginusers'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_title', models.CharField(max_length=100)),
                ('comment_details', models.CharField(max_length=100)),
                ('user_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='WebVul.loginusers')),
            ],
        ),
    ]
