# Generated by Django 4.1.2 on 2022-11-08 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebVul', '0003_usercomments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vul_Pages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vul_id', models.IntegerField()),
                ('vul_name', models.CharField(max_length=30)),
                ('vul_page', models.CharField(max_length=500)),
            ],
        ),
    ]
