# Generated by Django 4.1.2 on 2022-11-08 14:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('WebVul', '0004_vul_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='vul_pages',
            name='vul_title',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
