# Generated by Django 4.1.2 on 2022-12-10 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebVul', '0005_vul_pages_vul_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auth_Infos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_id', models.IntegerField()),
                ('info_content', models.CharField(max_length=300)),
                ('info_owner', models.CharField(max_length=300)),
            ],
        ),
    ]
