# Generated by Django 4.1.2 on 2022-12-14 11:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('WebVul', '0006_auth_infos'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginusers',
            name='user_email',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
